// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var req, url;
    url = 'skim.json';
    console.log(url);
    $.ajax({
      url: url,
      dataType: 'json',
      success: function() {
        return console.log('done');
      }
    });
    "Hello from skim!";

    return req = $.ajax({
      url: 'scripts/skim.json',
      dataType: 'json',
      success: function(e) {
        var imgArr;
        console.log(e);
        imgArr = [];
        $(e.skimlinksProductAPI.products).each(function() {
          return imgArr.push(this.imageUrl);
        });
        console.log(imgArr);
        $(imgArr).each(function() {
          var wrap;
          wrap = '<a data-gallery=""href=# ><img src=' + this + ' /></a>';
          return $('#gallery').append(wrap);
        });
        $('img').height('100');
        return $('img').each(function() {
          if ($(this).width() > 150) {
            return $(this).hide();
          }
        });
      }
    });
  });

}).call(this);
